# Generated by Django 5.2.8 on 2025-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('CU', 'Customer'), ('VE', 'Vendor')], max_length=2)),
                ('User_Name', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Password', models.CharField(max_length=100)),
                ('confirm_Password', models.CharField(max_length=100)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
